### PR TITLE
Demonstrate how to use the fable library

### PR DESCRIPTION
**Pull request by clssn**
A minimal example showing that it's easy to even use fable in your own
application, so outside Cloe.

I'm sure there's potential to improve! I wasn't too creative about the example structure. Maybe something more relatable? Didn't want to use the address book example...

---
This change is [Reviewable](https://reviewable.io/reviews/eclipse/cloe/44)

### CODE REVIEW

**Review by cassava — CHANGES_REQUESTED** [review]
I actually think the address book example is perfect, since you can compare it to the multitude of examples outside. I'll add that myself though.

Another thing: we should rename it, simple_config or something like that.

> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44#-:-MdGi3sO8QEXX8SGBquR:b-1nrxhr)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @clssn and @tobifalk)

___
*[fable/examples/minimal_application/.clang-format, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGg_tI65P9-0FqcfoA:-MdGg_tI65P9-0FqcfoB:b-oiq3fc) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.clang-format#L1)):*
> ```YAML
> ---
> ```

I don't think we need this file here, since we already have one in the repo.
___
*[fable/examples/minimal_application/.gitignore, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGgh7J7dd8OL-0NQ5C:-MdGgh7L6641-5dM-7Qe:bqs7jly) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.gitignore#L1)):*
> ```ignore
> build
> ```

To match directories, you need to suffix with `/`
___
*[fable/examples/minimal_application/conanfile.txt, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiFRzCc8uc_D0iKb7:-MdGiFRzCc8uc_D0iKb8:b-ucvma6) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/conanfile.txt#L3)):*
> ```help
> [requires]
> cli11/1.9.1
> fable/0.18.0-rc2@cloe/develop
> ```

This is unfortunate...
___
*[fable/examples/minimal_application/example.json, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiIDU-0OMYJcOceaD:-MdGiIDU-0OMYJcOceaE:b-t03we5) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/example.json#L3)):*
> ```JSON
> {
>   "is_cool": false,
>   "is_supercool": true,
> ```

I appreciate the gesture, but later readers won't know this doesn't come from the author and will perceive it as being pretentious perhaps?
___
*[fable/examples/minimal_application/Makefile, line 4 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiSvk43G5g4uOk8k6:-MdGiSvk43G5g4uOk8k7:b-mnkbn9) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/Makefile#L4)):*
> ```Makefile
> 	mkdir -p build
> 	conan install --build=missing --install-folder=build conanfile.txt
> 	cd build && cmake ..
> ```

There's a way to do this with cmake commands:

```make
.PHONY: help all install uninstall package clean
help:
	@echo "Usage: make <target>"
	@echo "Available setup targets:"
	@echo "  all        to build library"
	@echo "  install    to install built files"
	@echo "  uninstall  to uninstall previously installed files"
	@echo "  clean      to remove build directory and artifacts"

.PHONY: all
all: build
	cmake -E time cmake --build build

build:
	cmake -E make_directory build
	cmake -E chdir build cmake -E time cmake -Wdev ..

install: all
	make -C build install

uninstall: build
	cd build && test -f install_manifest.txt && xargs rm < install_manifest.txt

clean:
	-rm -r build
```
___
*[fable/examples/minimal_application/src/main.cpp, line 2 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGwmX45T_ZFvduXoTZ:-MdGwmX51ibN--6J9su_:b-7xte9g) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/src/main.cpp#L2)):*
> ```cpp
> /*
>  * Copyright 2020 Robert Bosch GmbH
> ```

Year.

**Review by clssn — COMMENTED** [review]
If you put it this way, I'll happily agree! Just do it :-)

> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44#-:-MdHKh0V4GSt0o1YHMfT:b-cjasr6)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @cassava and @tobifalk)

___
*[fable/examples/minimal_application/.clang-format, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGg_tI65P9-0FqcfoA:-MdHLJ7Y7Fy17qA_naOo:b-lq0354) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.clang-format#L1)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I don't think we need this file here, since we already have one in the repo.
</blockquote></details>

I agree, just copied the example from its own repo, where the file was top-level.
___
*[fable/examples/minimal_application/.gitignore, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGgh7J7dd8OL-0NQ5C:-MdHLRH89gAah81SR6tT:b-nzd9vk) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.gitignore#L1)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

To match directories, you need to suffix with `/`
</blockquote></details>

Hmm, I think it works fine, but with `/` it wouldn't match files anymore, so: agreed!
___
*[fable/examples/minimal_application/conanfile.txt, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiFRzCc8uc_D0iKb7:-MdHLhL-EOj6UrkhgBvj:b-p3pl7z) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/conanfile.txt#L3)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This is unfortunate...
</blockquote></details>

Well, I'd pick >=0.18.0, but rc2 is < I guess? Or do you mean something else but the fable version?
___
*[fable/examples/minimal_application/example.json, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiIDU-0OMYJcOceaD:-MdHLzkx-HnWCvOMJzMW:bpmrl26) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/example.json#L3)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I appreciate the gesture, but later readers won't know this doesn't come from the author and will perceive it as being pretentious perhaps?
</blockquote></details>

Resolved with switching to an addressbook example.
___
*[fable/examples/minimal_application/Makefile, line 4 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiSvk43G5g4uOk8k6:-MdHMDuv9zUQeYXwMBFL:b-88de9w) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/Makefile#L4)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

There's a way to do this with cmake commands:

```make
.PHONY: help all install uninstall package clean
help:
	@echo "Usage: make <target>"
	@echo "Available setup targets:"
	@echo "  all        to build library"
	@echo "  install    to install built files"
	@echo "  uninstall  to uninstall previously installed files"
	@echo "  clean      to remove build directory and artifacts"

.PHONY: all
all: build
	cmake -E time cmake --build build

build:
	cmake -E make_directory build
	cmake -E chdir build cmake -E time cmake -Wdev ..

install: all
	make -C build install

uninstall: build
	cd build && test -f install_manifest.txt && xargs rm < install_manifest.txt

clean:
	-rm -r build
```
</blockquote></details>

Well, for a simple example I'd try and keep it as simple as possible, not as "clean" as possible. So I'd go without help, install and uninstall. `make` would then already build:
```
.PHONY: all clean
all: build
	cmake --build build

build:
	cmake -E make_directory build
	cmake -E chdir build cmake -E time cmake -Wdev ..

clean:
	-rm -r build
```
___
*[fable/examples/minimal_application/src/main.cpp, line 2 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGwmX45T_ZFvduXoTZ:-MdHPzN61X-1-MQIXBZx:b-834n6i) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/src/main.cpp#L2)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Year.
</blockquote></details>

Oops.

**Review by clssn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44)* status: 6 of 7 files reviewed, 6 unresolved discussions (waiting on @cassava and @tobifalk)

___
*[fable/examples/minimal_application/.clang-format, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGg_tI65P9-0FqcfoA:-MdHRgb3A_UflV0rIsjW:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.clang-format#L1)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

I agree, just copied the example from its own repo, where the file was top-level.
</blockquote></details>

Done.
___
*[fable/examples/minimal_application/.gitignore, line 1 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGgh7J7dd8OL-0NQ5C:-MdHRiH_DfN7_5RDBisk:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/.gitignore#L1)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Hmm, I think it works fine, but with `/` it wouldn't match files anymore, so: agreed!
</blockquote></details>

Done.
___
*[fable/examples/minimal_application/Makefile, line 4 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiSvk43G5g4uOk8k6:-MdHRsyZ-hAXKqqghUPT:b-wsr3bf) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/Makefile#L4)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Well, for a simple example I'd try and keep it as simple as possible, not as "clean" as possible. So I'd go without help, install and uninstall. `make` would then already build:
```
.PHONY: all clean
all: build
	cmake --build build

build:
	cmake -E make_directory build
	cmake -E chdir build cmake -E time cmake -Wdev ..

clean:
	-rm -r build
```
</blockquote></details>

Fixup contains the above. Hope you're okay with that?
___
*[fable/examples/minimal_application/src/main.cpp, line 2 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGwmX45T_ZFvduXoTZ:-MdHRqdG-yaMDDIkcdac:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/src/main.cpp#L2)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Oops.
</blockquote></details>

Done.

**Review by cassava — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44)* status: all files reviewed, 3 unresolved discussions (waiting on @cassava, @clssn, and @tobifalk)

___
*[fable/examples/minimal_application/Makefile, line 4 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiSvk43G5g4uOk8k6:-MdLFNpH7Ux2edVJES-F:b-vcz9wr) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/Makefile#L4)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Fixup contains the above. Hope you're okay with that?
</blockquote></details>

That's fine. I just copied and pasted from another project.
___
*[fable/examples/minimal_application/conanfile.txt, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiFRzCc8uc_D0iKb7:-MdLElGR2qHx9DuzLs4E:bms2yk2) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/conanfile.txt#L3)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Well, I'd pick >=0.18.0, but rc2 is < I guess? Or do you mean something else but the fable version?
</blockquote></details>

Agreed. `>=0.18.0` is good.

**Review by cassava — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44)* status: all files reviewed, 3 unresolved discussions (waiting on @clssn and @tobifalk)

___
*[fable/examples/minimal_application/example.json, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiIDU-0OMYJcOceaD:-MdLFV2s7A_x7cjmhN9R:b6g83ze) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/example.json#L3)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Resolved with switching to an addressbook example.
</blockquote></details>

I'll commit my work then.

**Comment by clssn** [comment]
I rebased. LGTM now, your turn again @cassava .

**Review by cassava — APPROVED** [review]
> Reviewed 14 of 14 files at r3, 2 of 3 files at r4, 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tobifalk)

**Review by clssn — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/44#-:-MdQwjsW7ErTF68PsdVV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @tobifalk)

___
*[fable/examples/contacts/conanfile.txt, line 3 at r3](https://reviewable.io/reviews/eclipse/cloe/44#-MdNTSw_7LlnFBSNUFgX:-MdNTSwaDZIisKVo_8c6:b-flqtf5) ([raw file](https://github.com/eclipse/cloe/blob/78e3fcfd276211214bb1692e178c0d01ddb417bc/fable/examples/contacts/conanfile.txt#L3)):*
> ```help
> [requires]
> cli11/[~=1.9.1]
> fable/[>0.17.0]@cloe/develop
> ```

Does this work for you? Conan doesn't seem to support version ranges to cover -rc* or -nightly. Even the `include_prereleases=True` described [here](https://docs.conan.io/en/latest/versioning/version_ranges.html#version-ranges) doesn't do the trick. Probably
___
*[fable/examples/minimal_application/Makefile, line 4 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiSvk43G5g4uOk8k6:-MdNI8qZ1Cxvp4eS2M1J:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/Makefile#L4)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

That's fine. I just copied and pasted from another project.
</blockquote></details>

Done.
___
*[fable/examples/minimal_application/conanfile.txt, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiFRzCc8uc_D0iKb7:-MdNF40M7T7Re3CnXzNu:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/conanfile.txt#L3)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Agreed. `>=0.18.0` is good.
</blockquote></details>

Done.
___
*[fable/examples/minimal_application/example.json, line 3 at r1](https://reviewable.io/reviews/eclipse/cloe/44#-MdGiIDU-0OMYJcOceaD:-MdNFBPvA8DnJQE8VgJu:b5zzx3a) ([raw file](https://github.com/eclipse/cloe/blob/c7812c65198287ef25b151565a9376bd6f80f3c1/fable/examples/minimal_application/example.json#L3)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I'll commit my work then.
</blockquote></details>

`example_input.json` doesn't match the changed schema. I'll fix this.

**Pull request merged**
