### PR TITLE
Release/0.19.0

### PR DESCRIPTION
**Pull request by cassava**
This adds some commits to fix several Docker build problems I was having.
It also simplifies the Docker build tooling by throwing out what we don't use or need.
This makes maintenance in the long-term easier.

Review commit-by-commit for the easiest time.

### CODE REVIEW

**Comment by cassava** [comment]
Instructions on how to use Docker are now in the main README file, so you can read how to use Docker there.

In short, something like this: `make -f Makefile.docker ubuntu-20.04`

**Comment by cassava** [comment]
This should also resolve the issues addressed by #95, so maybe we can close that when this is merged.

**Review by scpa1055 — COMMENTED** [review]
Im not sure if this zlib/1.2.13 works with boost <1.70.

**Comment by cassava** [comment]
> Im not sure if this zlib/1.2.13 works with boost <1.70.

I can't reproduce this. Could you provide some more details?

**Comment by scpa1055** [comment]
Never mind! 
It works fine.
PR looks good to me

**Review by scpa1055 — APPROVED** [review]
LGTM

**Pull request merged**
