### PR TITLE
Henning/vtd multi agent

### PR DESCRIPTION
**Pull request by clssn**
This feature branch enables Cloe's VTD binding to perform multi-agent simulation.
_**Attention**_: We need to **first finish the [`ben/add-vtd-package` PR](https://github.com/eclipse/cloe/pull/3)** and then rebase this one here onto the resulting master.

---
This change is [Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)

### CODE REVIEW

**Review by cassava — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 6 unresolved discussions (waiting on @clssn)

___
*[plugins/vtd/src/vtd_binding.cpp, line 206 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwT-ZB1u7NrQzqgzL:-MScwT-ZB1u7NrQzqgzM:bqunvd5) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L206)):*
> ```cpp
>       // Wait for creation of TaskControl client
>       logger()->info("Wait for task control...");
>       scp_try_read_until([this]() { return static_cast<bool>(task_control_); });
> ```

return task_control_ != nullptr;
___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MScwopODeCMbJYfU0vo:b-wbl6qa) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
> ```cpp
>       if (!config_.scenario.size()) {
>         logger()->info("Wait for scenario...");
>         scp_try_read_until([this]() { return config_.scenario.size(); });
> ```

I would say use `scenario != ""` since the intention is clearer.
Otherwise I think it's best practice to not use 0 == false shortcuts and write it out explicitely for those things...
___
*[plugins/vtd/src/vtd_binding.cpp, line 212 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScuM3J3Kc-zK-mIdVO:-MScuM3K4xWWxwNBZGAw:b-99i9xl) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L212)):*
> ```cpp
>         logger()->info("Wait for scenario...");
>         scp_try_read_until([this]() { return config_.scenario.size(); });
>         // Stop to neutralize GUI's Init command sendt along with LoadScenario
> ```

Typo: "sent"
___
*[plugins/vtd/src/vtd_binding.cpp, line 220 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScxgFN84Zx_a8aOP5v:-MScxgFOEWfKqG-ZCy6L:bxm2j61) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L220)):*
> ```cpp
>       query.scenario = config_.scenario;
>       scp_client_->send(query);
>       scp_try_read_until([this]() { return !agents_expected_.empty(); });
> ```

We should note for all these `scp_try_read_until` function calls note where we expect the predicate to be set to true.
___
*[plugins/vtd/src/vtd_binding.cpp, line 464 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScw3qI4EDNwRc2aScZ:-MScw3qJ5vBcYeqPhlUe:b-vwrujn) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L464)):*
> ```cpp
>    */
>   void scp_try_read_until(std::function<bool(void)> pred) {
>     int tries_left = VTD_INIT_WAIT_RETRIES;
> ```

I thought VtdConf had a value for this...
___
*[plugins/vtd/src/vtd_binding.cpp, line 616 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MSfzACV7BtaGNw3pgUG:-MSfzACV7BtaGNw3pgUH:bcxwzbr) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L616)):*
> ```cpp
>     if (p.is_absolute()) {
>       // make relative to first subdirectory called "Scenarios"
>       auto s = std::find(p.begin(), p.end(), "Scenarios");
> ```

Print a warning if the path has more than one "Scenarios" element, letting the user know why this might be a problem.

**Review by clssn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 6 unresolved discussions (waiting on @cassava and @clssn)

___
*[plugins/vtd/src/vtd_binding.cpp, line 464 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScw3qI4EDNwRc2aScZ:-MSg6n9f53nOBZuEKS5J:b-ns5wlt) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L464)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I thought VtdConf had a value for this...
</blockquote></details>

We have individual TcpTransceiverConfiguration used for connecting to scp, paramserver, taskcontrol and the sensors. But there we want to sleep longer between the retries. It would stall initialization if we'd wait for seconds here. I propose to leave the sleep duration a constant and re-use the number of retries from the scp transceiver's config.

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 464 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScw3qI4EDNwRc2aScZ:-MSgDL628k54nUfJ-h6N:bxc1cp3) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L464)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

We have individual TcpTransceiverConfiguration used for connecting to scp, paramserver, taskcontrol and the sensors. But there we want to sleep longer between the retries. It would stall initialization if we'd wait for seconds here. I propose to leave the sleep duration a constant and re-use the number of retries from the scp transceiver's config.
</blockquote></details>

Hm, sure. We can always add a configuration value later if we need it.

**Review by clssn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @cassava)

___
*[plugins/vtd/src/vtd_binding.cpp, line 206 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwT-ZB1u7NrQzqgzL:-MSh3a0dBVM1JuqrrNOf:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L206)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

return task_control_ != nullptr;
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MSh3ail6mJ5Z0517DFa:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I would say use `scenario != ""` since the intention is clearer.
Otherwise I think it's best practice to not use 0 == false shortcuts and write it out explicitely for those things...
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 212 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScuM3J3Kc-zK-mIdVO:-MSh3c6G9atcuYoIWKeP:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L212)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Typo: "sent"
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 220 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScxgFN84Zx_a8aOP5v:-MSh3cyM-wNIAkQDsapS:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L220)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

We should note for all these `scp_try_read_until` function calls note where we expect the predicate to be set to true.
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 464 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScw3qI4EDNwRc2aScZ:-MSh3e5jCjmBKs4T6fGJ:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L464)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Hm, sure. We can always add a configuration value later if we need it.
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 616 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MSfzACV7BtaGNw3pgUG:-MSh3ehWDMys7pnV23Ze:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L616)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Print a warning if the path has more than one "Scenarios" element, letting the user know why this might be a problem.
</blockquote></details>

Done.

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 212 at r5](https://reviewable.io/reviews/eclipse/cloe/12#-MSh4KWH5vcdZVlXsGOm:-MSh4KWI45KpkdW0tXTo:b1901j) ([raw file](https://github.com/eclipse/cloe/blob/4f66f7e8c6d92eda629b88fe26133b2a9f7c8d3f/plugins/vtd/src/vtd_binding.cpp#L212)):*
> ```cpp
>       if (!config_.scenario.size()) {
>         logger()->info("Wait for scenario...");
>         // Expect the scenario to be initialized in VtdBiniding::apply_scenario_filename()
> ```

Typo: VtdBiniding

**Comment by clssn** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 212 at r5](https://reviewable.io/reviews/eclipse/cloe/12#-MSh4KWH5vcdZVlXsGOm:-MSh4mky5Xnxc5dfpRJW:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/4f66f7e8c6d92eda629b88fe26133b2a9f7c8d3f/plugins/vtd/src/vtd_binding.cpp#L212)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Typo: VtdBiniding
</blockquote></details>

Done.

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 616 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MSfzACV7BtaGNw3pgUG:-MSh4w8cEXp8UvQ6cG4P:b-yjp6ut) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L616)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You missed this one.

**Review by cassava — COMMENTED** [review]
> Reviewed 2 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @cassava and @clssn)

**Review by cassava — COMMENTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @cassava and @clssn)

**Review by cassava — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 1 unresolved discussion (waiting on @clssn)

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 629 at r8](https://reviewable.io/reviews/eclipse/cloe/12#-MShIcfP1gl4qHmkRu-h:-MShIcfQ-Hf3uMCRduKf:bz4i5b4) ([raw file](https://github.com/eclipse/cloe/blob/982b5a2c937e3a49c5ded2f97ed8dc0c41293e1f/plugins/vtd/src/vtd_binding.cpp#L629)):*
> ```cpp
>       }
>       fs::path r;
>       for (auto it = ++s; it != p.end(); ++it) r /= *it;
> ```

Missing { brackets } around content of for-loop :-(

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 632 at r8](https://reviewable.io/reviews/eclipse/cloe/12#-MShIwsaCbg2EL3uVOjA:-MShIwsaCbg2EL3uVOjB:b-m7d9f4) ([raw file](https://github.com/eclipse/cloe/blob/982b5a2c937e3a49c5ded2f97ed8dc0c41293e1f/plugins/vtd/src/vtd_binding.cpp#L632)):*
> ```cpp
>       if (std::find(s, p.end(), "Scenarios") != p.end()) {
>         logger()->warn(
>             "Cannot determine the scenario directory unambiguously because"
> ```

This is not going to look great printed...
"unambiguously becausethe chosen"

**Review by cassava — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 3 unresolved discussions (waiting on @clssn)

**Review by clssn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 3 unresolved discussions (waiting on @cassava)

___
*[plugins/vtd/src/vtd_binding.cpp, line 616 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MSfzACV7BtaGNw3pgUG:-MShJMIlCmO0S7wYVc5Z:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L616)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

You missed this one.
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 629 at r8](https://reviewable.io/reviews/eclipse/cloe/12#-MShIcfP1gl4qHmkRu-h:-MShIth19pFi9UTWzn1n:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/982b5a2c937e3a49c5ded2f97ed8dc0c41293e1f/plugins/vtd/src/vtd_binding.cpp#L629)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Missing { brackets } around content of for-loop :-(
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 632 at r8](https://reviewable.io/reviews/eclipse/cloe/12#-MShIwsaCbg2EL3uVOjA:-MShJhpB2xGMhozoVrMY:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/982b5a2c937e3a49c5ded2f97ed8dc0c41293e1f/plugins/vtd/src/vtd_binding.cpp#L632)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

This is not going to look great printed...
"unambiguously becausethe chosen"
</blockquote></details>

Done.

**Review by cassava — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12#-:-MShKDCi7Sh2Ud2nVsh-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by clssn — COMMENTED** [review]
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Comment by cassava** [comment]
Goood catch!

**Review by cassava — APPROVED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by clssn — COMMENTED** [review]
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by cassava — APPROVED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by tobifalk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, 2 of 3 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 1 unresolved discussion (waiting on @clssn)

___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MShDVG28yGQL_oPlq7P:b-4v61dl) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are a couple more `config_.scenario.size()` in this file. Should those be changed as well?
___
*[plugins/vtd/src/vtd_binding.cpp, line 324 at r6](https://reviewable.io/reviews/eclipse/cloe/12#-MShCdj6EihHi--bxxDU:-MShCdj6EihHi--bxxDV:b9zti49) ([raw file](https://github.com/eclipse/cloe/blob/8c00bd6bcdfe2d63321b41d7225c0f988b4d68c8/plugins/vtd/src/vtd_binding.cpp#L324)):*
> ```cpp
> 
>     // If in reset, block until VTD sends "Run" again then start next cycle
>     while (!operational_) {
> ```

Should we take this chance to replace `operational_` by ` is_operational()`?

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 324 at r6](https://reviewable.io/reviews/eclipse/cloe/12#-MShCdj6EihHi--bxxDU:-MShQdw_-1mdi4ER9M9n:blh64sn) ([raw file](https://github.com/eclipse/cloe/blob/8c00bd6bcdfe2d63321b41d7225c0f988b4d68c8/plugins/vtd/src/vtd_binding.cpp#L324)):*
<details><summary><i>Previously, tobifalk (Tobias Falkenstein) wrote…</i></summary><blockquote>

Should we take this chance to replace `operational_` by ` is_operational()`?
</blockquote></details>

I'd rather do it the other way around. Because `is_operational()` is an interface method and probably shouldn't be used internally for more than it externally promises...
Also `operational_` is easy to search for where it is changed.

**Comment by clssn** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MShQoW22VqGG8yAGLoL:b-9ksiml) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, tobifalk (Tobias Falkenstein) wrote…</i></summary><blockquote>

There are a couple more `config_.scenario.size()` in this file. Should those be changed as well?
</blockquote></details>

Yes, definitely. Thanks!

**Comment by cassava** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MShQwnJ2TXglhlw5pwS:bm2nx08) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Yes, definitely. Thanks!
</blockquote></details>

Yes please? There's also `empty()` isn't there?

**Comment by clssn** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 324 at r6](https://reviewable.io/reviews/eclipse/cloe/12#-MShCdj6EihHi--bxxDU:-MShRKGg5XmjDVOOCirN:b-pbdqz3) ([raw file](https://github.com/eclipse/cloe/blob/8c00bd6bcdfe2d63321b41d7225c0f988b4d68c8/plugins/vtd/src/vtd_binding.cpp#L324)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

I'd rather do it the other way around. Because `is_operational()` is an interface method and probably shouldn't be used internally for more than it externally promises...
Also `operational_` is easy to search for where it is changed.
</blockquote></details>

Agreed.

**Review by cassava — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 2 unresolved discussions (waiting on @clssn)

**Comment by clssn** [comment]
___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MShSVS-8iUb_ZaZebgZ:btwor4d) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, cassava (Ben Morgan) wrote…</i></summary><blockquote>

Yes please? There's also `empty()` isn't there?
</blockquote></details>

No empty() in strings. Only size().

**Review by clssn — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 2 unresolved discussions (waiting on @cassava and @tobifalk)

___
*[plugins/vtd/src/vtd_binding.cpp, line 211 at r3](https://reviewable.io/reviews/eclipse/cloe/12#-MScwopODeCMbJYfU0vn:-MShScFL2DoDgPzJcDMj:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/a71b9488a23a76deed3ed8ef10a32640db533bcf/plugins/vtd/src/vtd_binding.cpp#L211)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

No empty() in strings. Only size().
</blockquote></details>

Done.
___
*[plugins/vtd/src/vtd_binding.cpp, line 324 at r6](https://reviewable.io/reviews/eclipse/cloe/12#-MShCdj6EihHi--bxxDU:-MShSdU91DrbZUOhg47s:b-896fix) ([raw file](https://github.com/eclipse/cloe/blob/8c00bd6bcdfe2d63321b41d7225c0f988b4d68c8/plugins/vtd/src/vtd_binding.cpp#L324)):*
<details><summary><i>Previously, clssn (Henning Claßen) wrote…</i></summary><blockquote>

Agreed.
</blockquote></details>

Done.

**Review by tobifalk — COMMENTED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 2 unresolved discussions (waiting on @cassava and @tobifalk)

**Review by cassava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: all files reviewed, 1 unresolved discussion (waiting on @tobifalk)

**Review by tobifalk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by tobifalk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by cassava — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12#-:-MShVUJa6gxfLSjGiWe_:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @cassava)

**Review by tobifalk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12#-:-MShVYUFBL8Q3D-NFjQk:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @cassava)

**Review by cassava — COMMENTED** [review]
> Reviewed 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @cassava)

**Review by cassava — APPROVED** [review]
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by clssn — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12#-:-MShVssg0tHu-gy1tDQK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by cassava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Review by tobifalk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eclipse/cloe/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clssn)

**Pull request merged**
