### PR TITLE
fable: Fix excessive compilation duration

### PR DESCRIPTION
**Pull request by clsim**
Users of fable experienced compilation durations up to 12h. This PR is delivering a proven-in-use mitigation.

### CODE REVIEW

**Comment by cassava** [comment]
Looks great, thanks for the work!

**Comment by cassava** [comment]
I'd merge this to master, to make it part of 0.21, and if requested, we can also backport this to 0.20 and 0.19. What do you think?

**Comment by clsim** [comment]
Thank you! A backport is not needed since the users have the same as a workaround and want to upgrade to develop soon.

**Comment by cassava** [comment]
Force-push: Removed formatting of code in order to better apply to `master` branch.

**Comment by cassava** [comment]
Update: I've been attempting to get a positive result in before-after testing. So far I've been unsuccessful.

I've added a stress test that *should* be representative of problematic use-cases. I've been able to reproduce long compile times up to over an hour for a single file. However, the patch
doesn't seem to be able to reduce this compile time.

@clsim Could you have a look at this and see if I've missed something or made a mistake somewhere?

**Comment by cassava** [comment]
Here are the steps that can be used to compile and run the stress test:

```bash
git clone https://github.com/eclipse/cloe
cd cloe
git switch clsim/bugfix-make-schema
make -f Makefile.docker build-ubuntu-20.04 run-ubuntu-20.04
cd fable/examples/stress
make all
# -> This probably fails because cmake is too old on ubuntu:20.04 image,
#    but Conan tells us how to call cmake.
cd build/Release
cmake ../.. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=/cloe/fable/examples/stress/build/Release/generators/conan_toolchain.cmake -DCMAKE_POLICY_DEFAULT_CMP0091=NEW -DCMAKE_BUILD_TYPE=Release
time make all
```

With the default settings, this last command `time make all` takes 1min. You can increase this by passing in a different value to the **first** make call in the container with `make all LARGE_STRUCT_SIZE=10000`.

**Comment by clsim** [comment]
> Update: I've been attempting to get a positive result in before-after testing. So far I've been unsuccessful.

While my measurements I aborted after 40minutes the compilation. Already that is 5x worse compared to the unpatched(!) state which gave the reason for the PR.

**Comment by cassava** [comment]
After some more work with @hvolx we managed to discover the issue and fix it. Essentially, perfect forwarding the `desc` type resolves the issue o_O

**Review by cassava — APPROVED** [review]

**Review by clsim — COMMENTED** [review]
Looks good for me

**Pull request merged**
